### ISSUE TITLE
Please use `files` in `package.json`

### ISSUE THREAD

**Issue by shellscape** [WebScrapingAPI/rand-user-agent#9]
By not using `files`, you're publishing the _entire directory_ to NPM. Here's a screenshot of the contents of the package tar.

<img width="215" alt="Screen Shot 2022-10-31 at 1 31 39 PM" src="https://user-images.githubusercontent.com/76371/199071855-0b71698c-2bc4-4ad0-be47-2f8ecb38c4d9.png">

Please use this https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files.

**Comment by Mihai-Maxim** [comment]
We migrated to ESM and cleaned the published files. Thank you for the feedback!
